PoolSaison2019/PoolSaison2019/Models/ErrorViewModel.cs
using System;

namespace PoolSaison2019.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PoolSaison2019/PoolSaison2019/Models/Joueur.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PoolSaison2019.Models
{
    public class Joueur : Entity
    {
        public string Nom { get; set; }
        public string Equipe { get; set; }
        public string Position { get; set; }
        public int Salaire { get; set; }
    }
}

PoolSaison2019/PoolSaison2019/Models/Participant.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PoolSaison2019.Models
{
    public class Participant : Entity
    {
        public string Nom { get; set; }
        public string Rang { get; set; }
        public string LastWeekRank { get; set; }
        public int Gains { get; set; }
    }
}

PoolSaison2019/PoolSaison2019/Models/Signatures.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PoolSaison2019.Models
{
    public class Signatures : Entity
    {
        public string Nom { get; set; }
        public string Ville { get; set; }
    }
}

PoolSaison2019/PoolSaison2019/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PoolSaison2019.Models;

namespace PoolSaison2019.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PoolSaison2019/PoolSaison2019/Controllers/JoueursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PoolSaison2019.Data;
using PoolSaison2019.Models;

namespace PoolSaison2019.Controllers
{
    public class JoueursController : Controller
    {
        private readonly PoolSaison2019Context _context;

        private IRepository<Joueur> _joueurRepository;

        public JoueursController(IRepository<Joueur> joueurRepository)
        {
            _joueurRepository = joueurRepository;
        }

        // GET: Joueurs
        public async Task<IActionResult> Index()
        {
            return View(await _joueurRepository.GetAll());
        }

       /* // GET: Joueurs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joueur = await _context.Joueur
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joueur == null)
            {
                return NotFound();
            }

            return View(joueur);
        }

        // GET: Joueurs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Joueurs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Equipe,Position,Salaire")] Joueur joueur)
        {
            if (ModelState.IsValid)
            {
                _context.Add(joueur);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(joueur);
        }

        // GET: Joueurs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joueur = await _context.Joueur.FindAsync(id);
            if (joueur == null)
            {
                return NotFound();
            }
            return View(joueur);
        }

        // POST: Joueurs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Equipe,Position,Salaire")] Joueur joueur)
        {
            if (id != joueur.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(joueur);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JoueurExists(joueur.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(joueur);
        }

        // GET: Joueurs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var joueur = await _context.Joueur
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joueur == null)
            {
                return NotFound();
            }

            return View(joueur);
        }

        // POST: Joueurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var joueur = await _context.Joueur.FindAsync(id);
            _context.Joueur.Remove(joueur);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JoueurExists(int id)
        {
            return _context.Joueur.Any(e => e.Id == id);
        }*/
    }
}

PoolSaison2019/PoolSaison2019/Controllers/ParticipantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PoolSaison2019.Data;
using PoolSaison2019.Models;

namespace PoolSaison2019.Controllers
{
    public class ParticipantsController : Controller
    {
        private IRepository<Participant> _participantRepository;

        public ParticipantsController(IRepository<Participant> participantRepository)
        {
            _participantRepository = participantRepository;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _participantRepository.GetAll());
        }
    }
}

PoolSaison2019/PoolSaison2019/Controllers/SignaturesController.cs
using Microsoft.AspNetCore.Mvc;
using PoolSaison2019.Data;
using PoolSaison2019.Models;
using System.Threading.Tasks;

namespace PoolSaison2019.Controllers
{
    public class SignaturesController : Controller
    {
        private IRepository<Signatures> _signaturesRepository;

        public SignaturesController(IRepository<Signatures> signaturesRepository)
        {
            _signaturesRepository = signaturesRepository;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _signaturesRepository.GetAll());
        }
        public IActionResult SignatureRecente(string name, string ville, string id = "-1")
        {
            ViewData["id"] = id;
            ViewData["name"] = name;
            ViewData["ville"] = ville;
            return View();
        }
    }
}

PoolSaison2019/PoolSaison2019/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PoolSaison2019/PoolSaison2019/Views/Joueurs/Create.cshtml
@model PoolSaison2019.Models.Joueur

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Joueur</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Equipe" class="control-label"></label>
                <input asp-for="Equipe" class="form-control" />
                <span asp-validation-for="Equipe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salaire" class="control-label"></label>
                <input asp-for="Salaire" class="form-control" />
                <span asp-validation-for="Salaire" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PoolSaison2019/PoolSaison2019/Views/Joueurs/Delete.cshtml
@model PoolSaison2019.Models.Joueur

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Joueur</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Equipe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Equipe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salaire)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salaire)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PoolSaison2019/PoolSaison2019/Views/Joueurs/Details.cshtml
@model PoolSaison2019.Models.Joueur

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Joueur</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Equipe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Equipe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salaire)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salaire)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PoolSaison2019/PoolSaison2019/Views/Joueurs/Edit.cshtml
@model PoolSaison2019.Models.Joueur

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Joueur</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Equipe" class="control-label"></label>
                <input asp-for="Equipe" class="form-control" />
                <span asp-validation-for="Equipe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salaire" class="control-label"></label>
                <input asp-for="Salaire" class="form-control" />
                <span asp-validation-for="Salaire" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PoolSaison2019/PoolSaison2019/Views/Joueurs/Index.cshtml
@model IEnumerable<PoolSaison2019.Models.Joueur>

@{
    ViewData["Title"] = "Index";
}

<h1>Joueurs de la ligue</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Equipe)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salaire)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Equipe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salaire)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PoolSaison2019/PoolSaison2019/Views/Participants/Index.cshtml
@model IEnumerable<PoolSaison2019.Models.Participant>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Participants";
}

<h1>Liste des participants</h1>
@foreach (var item in Model)
{
    <div>
        <span><B>No:</B> @Html.DisplayFor(modelItem => item.Id) </span>
        <span><B>Name:</B> @Html.DisplayFor(modelItem => item.Nom) </span>
        <span><B>Gains:</B> @Html.DisplayFor(modelItem => item.Gains) </span>
        <span><B>Rang:</B> @Html.DisplayFor(modelItem => item.Rang) </span>
        <span><b>Rang de la semaine passé:</b> @Html.DisplayFor(modelItem => item.LastWeekRank) </span>
        <br />
    </div>
}

PoolSaison2019/PoolSaison2019/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PoolSaison2019</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PoolSaison2019</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Signatures" asp-action="Index">Signatures</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Participants" asp-action="Index">Participants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Joueurs" asp-action="Index">Joueurs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - PoolSaison2019 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PoolSaison2019/PoolSaison2019/Views/Signatures/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Index";
}
<h1>Signatures de contrat</h1>
<p>Liste des dernières signatures de contrat dans la ligue.</p>

PoolSaison2019/PoolSaison2019/Views/Signatures/SignatureRecente.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <h1>Dernière signature de contrat</h1>
    @if ((string)ViewData["id"] != "-1" && (string)ViewData["id"] != "99")
    {
        <table >
            <tr>
                <td>Numéro: @ViewData["id"]</td>
            </tr>
            <tr>
                <td>Nom: @ViewData["name"]</td>
            </tr>
            <tr>
                <td>Équipe: @ViewData["ville"]</td>
</tr>
        </table>
    }
    else
    {
        <p>Signature en cours mais non officialisée</p>
    }
}